---
site_name: "INCLUDE LinkML Data Model"
theme:
  name: material
  # palette:
  #  scheme: slate
  #  primary: cyan
  features:
    - content.tabs.link

# for adding extra css/js see https://www.mkdocs.org/user-guide/customizing-your-theme/

plugins:
  - search
  - mknotebooks:
      execute: false
  - mermaid2:
      version: 11.4.1
  # TODO rebuild docs on schema change (https://github.com/dalito/linkml-project-copier/issues/39)
  # - gen-files:
  #     scripts:
  #       - gen_pages.py  # or any other name or path

watch:
  - src/include_linkml_data_model/schema

nav:
  - Home: index.md
  - Schema: elements/index.md
  - About: about.md

exclude_docs: |
  /templates-linkml/

site_url: https://include-dcc.github.io/INCLUDE LinkML Data Model
repo_url: https://github.com/include-dcc/INCLUDE LinkML Data Model

# Uncomment this block to enable use of Google Analytics.
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
